@extends('print.layout')

@section('title', $formCode.' · '.$slip->slip_no.' | APICS')

@push('styles')
<style>
    .print-table { width: 100%; border-collapse: collapse; margin: 0 0 16px; }
    .print-table th, .print-table td {
        border: 1px solid var(--rule);
        padding: 7px 8px;
        text-align: left;
        vertical-align: top;
        font-size: 12px;
    }
    .print-table th {
        background: var(--band);
        font-size: 10px;
        text-transform: uppercase;
        letter-spacing: 0.05em;
        color: var(--muted);
    }
    .section-title {
        font-size: 13px;
        font-weight: 700;
        margin: 0 0 8px;
        padding-bottom: 4px;
        border-bottom: 1px solid var(--rule);
    }
</style>
@endpush

@section('content')
    @include('print.partials.letterhead', [
        'formCode' => $formCode,
        'formTitle' => $formTitle,
        'documentNo' => $slip->slip_no,
        'subtitle' => $slip->application?->project_title,
    ])

    <section class="meta">
        <div>
            <span class="meta__label">Application</span>
            <span class="meta__value">{{ $slip->application?->application_no ?? '—' }}</span>
        </div>
        <div>
            <span class="meta__label">Classification</span>
            <span class="meta__value">{{ $slip->classification?->value ?? $slip->classification }}</span>
        </div>
        <div>
            <span class="meta__label">Template</span>
            <span class="meta__value">{{ $slip->template?->code ?? '—' }} · {{ $slip->template?->name ?? '' }}</span>
        </div>
        <div>
            <span class="meta__label">Generated</span>
            <span class="meta__value">{{ optional($slip->generated_at)->format('M d, Y · h:i A') ?? '—' }}</span>
        </div>
        <div>
            <span class="meta__label">Generated by</span>
            <span class="meta__value">{{ $slip->generatedBy?->name ?? '—' }}</span>
        </div>
        <div>
            <span class="meta__label">Status</span>
            <span class="meta__value">{{ $slip->status }}</span>
        </div>
    </section>

    <h2 class="section-title">{{ $doc === 'qms-62' ? 'Routing path (QMS-62)' : 'Route offices (QMS-61)' }}</h2>
    <table class="print-table">
        <thead>
            <tr>
                <th style="width:48px">#</th>
                <th>Office / step</th>
                <th>Department</th>
                <th style="width:110px">Status</th>
                <th>Notes</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($slip->steps as $step)
                <tr>
                    <td>{{ $step->step_order }}</td>
                    <td>{{ $step->label }}</td>
                    <td>{{ $step->department?->name ?? $step->department?->code ?? '—' }}</td>
                    <td>{{ strtoupper((string) ($step->status?->value ?? $step->status)) }}</td>
                    <td>{{ $step->notes ?? '' }}</td>
                </tr>
            @empty
                <tr><td colspan="5">No routing steps recorded.</td></tr>
            @endforelse
        </tbody>
    </table>

    <section class="signatures">
        <div class="sig">
            <div class="sig__line"></div>
            <div class="sig__name">{{ $slip->generatedBy?->name ?? '' }}</div>
            <div class="sig__role">Prepared by</div>
        </div>
        <div class="sig">
            <div class="sig__line"></div>
            <div class="sig__role">Receiving office</div>
        </div>
        <div class="sig">
            <div class="sig__line"></div>
            <div class="sig__role">City Building Official</div>
        </div>
    </section>

    <footer class="footer">
        <span>System-generated document · APICS · CSFP OCBO · Not valid without authorized signature when required.</span>
        <span>Printed {{ now()->format('M d, Y · h:i A') }}</span>
    </footer>
@endsection
